### ISSUE TITLE
Colaboradores

### ISSUE THREAD

**Issue by kelly-u** [kelly-u/GCMS-Gleice-Silva#1]
[README](https://github.com/kelly-u/GCMS-Gleice-Silva/edit/main/README.md)

**Comment by ramidedantas** [comment]
@kelly-u tem um espaço entre o ] e (, por isso o link não está correto. Corrija e me marque aqui.

**Comment by kelly-u** [comment]
[README]([https://github.com/kelly-u/GCMS-Gleice-Silva#readme](https://github.com/kelly-u/GCMS-Gleice-Silva/issues/url))

**Comment by kelly-u** [comment]
@ramidedantas

**Comment by kelly-u** [comment]
@ramidedantas

**Comment by ramidedantas** [comment]
@kelly-u link parece não estar correto ainda

**Comment by ramidedantas** [comment]
@kelly-u aguardando correção.

**Comment by kelly-u** [comment]
@ramidedantas link ajustado.

**Comment by ramidedantas** [comment]
@kelly-u Coloque o README no mesmo formato que está no meu repositório.

**Comment by kelly-u** [comment]
@ramidedantas Feito

**Comment by ramidedantas** [comment]
Ok @kelly-u, pode fechar a issue
